name: Garage Apartment FTW
favicon: null
layout_spectrum: 0.75606
typography_spectrum: 0.19377
title: 'A Build Guide and Thought Experiment '
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-75850507-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fffffd'
    - '#d7dbdc'
    - '#98a0ab'
    - '#526283'
    - '#2c2d1d'
  brandStrength: 0.375
  lightness: 0.5625
  saturation: 0.1875
  rhythmicContrast: 0.5
purpose: []
